In [1]:
import numpy 

In [28]:
#Passing elements in a list
numpy_arr= numpy.array([12,3,4,5])
print(numpy_arr)
print(numpy_arr.ndim)
print(type(numpy_arr))
print(type(numpy_arr.dtype))

#passing a tuple
numpy_arr= numpy.array((12,'abcd',4,5))
print(numpy_arr)
print(type(numpy_arr))
print(type(numpy_arr.dtype))

#passing a list
numpy_arr= numpy.array([12,'abcd',4,5])
print(numpy_arr)
print(numpy_arr.ndim)
print(numpy_arr.size)

print(type(numpy_arr))
print(numpy_arr.dtype)
print(numpy_arr.shape)




[12  3  4  5]
1
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int64DType'>
['12' 'abcd' '4' '5']
<class 'numpy.ndarray'>
<class 'numpy.dtypes.StrDType'>
['12' 'abcd' '4' '5']
1
4
<class 'numpy.ndarray'>
<U21
(4,)


In [29]:
#2 d arrray 3X4
numpy_arr = numpy.array([[1,2,3,4],[11,12,13,14],[21,22,23,24]])
print(type(numpy_arr))
print(numpy_arr.size)
print(numpy_arr.ndim)
print(numpy_arr.dtype)
print(numpy_arr.shape)


<class 'numpy.ndarray'>
12
2
int64
(3, 4)


In [30]:
#3 d arrray 3X4
numpy_arr = numpy.array([
    [
        [1,2,3,4],[11,12,13,14],[21,22,23,24]
    ],
    [
        [101,102,103,104],[111,112,113,114],[121,122,123,124]
    ]
])
print(type(numpy_arr))
print(numpy_arr.size)
print(numpy_arr.ndim)
print(numpy_arr.dtype)
print(numpy_arr.shape)

<class 'numpy.ndarray'>
24
3
int64
(2, 3, 4)


Built in function to generate numpy array

In [33]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
numpy.arange(50, 55)

array([50, 51, 52, 53, 54])

In [35]:
numpy.arange(50, 80, 5)

array([50, 55, 60, 65, 70, 75])

In [36]:
##Generate all ones
numpy.ones(3)

array([1., 1., 1.])

In [37]:
numpy.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
numpy.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# zeroes
numpy.zeros(3)

array([0., 0., 0.])

In [42]:
numpy.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [43]:
# Ideentity matrix
numpy.eye(1)


array([[1.]])

In [46]:
numpy.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [47]:
numpy.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# Generate array with same elements
numpy.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [55]:
#Generate linearly spaced values between 1 to 5
arr = numpy.linspace(1,5)
print(arr.size)
arr

50


array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [60]:
# Generate 10 values between 1 to 100 
numpy.linspace(1,100, num=10)
numpy.linspace(1,1000, num=10, retstep=True) # retStep=True gives 111 which is diff between 2 elemts

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 np.float64(111.0))

In [62]:
# Generate  1 random integer between a range
numpy.random.randint(1,100)

10

In [63]:
numpy.random.randint(1,100, 5)

array([34, 35, 24, 65, 82])

In [64]:
numpy.random.randint(1,100, size=(2,2))

array([[24, 11],
       [69, 85]])

In [65]:
#Function rand() : to generate values between 0 and 1
numpy.random.rand(10)

array([0.30903057, 0.21823382, 0.87987289, 0.63955472, 0.22159381,
       0.91539139, 0.03550451, 0.62136959, 0.77856978, 0.37060979])

In [66]:
numpy.random.rand(100)

array([0.22519753, 0.81755462, 0.97925065, 0.85874417, 0.98977935,
       0.96518025, 0.65848471, 0.95553839, 0.50663385, 0.28470611,
       0.43736914, 0.61521493, 0.01619972, 0.78288737, 0.16767401,
       0.37200148, 0.0295317 , 0.55402212, 0.14511482, 0.81684036,
       0.31469778, 0.44265897, 0.47144772, 0.98692206, 0.70809387,
       0.96048799, 0.19872482, 0.25224039, 0.61887556, 0.20686127,
       0.93469134, 0.93943899, 0.90081051, 0.4761436 , 0.91169973,
       0.08146305, 0.25699118, 0.23930105, 0.40157084, 0.27235364,
       0.38432602, 0.36112754, 0.11872118, 0.04939775, 0.79216997,
       0.74242503, 0.51397026, 0.42183029, 0.72812886, 0.43606624,
       0.8533305 , 0.86940038, 0.64386971, 0.96078403, 0.68825172,
       0.54335298, 0.20411826, 0.42872267, 0.19907982, 0.12801222,
       0.29576757, 0.63366949, 0.62819865, 0.81750404, 0.68742811,
       0.76643201, 0.13297635, 0.21164137, 0.56718697, 0.25164993,
       0.69166961, 0.57367639, 0.93131422, 0.88550686, 0.17253

In [69]:
numpy.random.rand(2,2)

array([[0.520485  , 0.13327936],
       [0.08921604, 0.54591523]])

In [70]:
numpy.random.rand(7,2)

array([[6.78926837e-01, 1.03890612e-02],
       [8.78269100e-01, 8.33288988e-01],
       [2.72121324e-01, 5.06564937e-02],
       [7.61793945e-01, 4.36332478e-01],
       [8.91018344e-01, 9.12071266e-01],
       [3.55342787e-01, 8.60289679e-01],
       [7.56864638e-01, 9.00723585e-05]])

In [72]:
#Generate random numbers from normal distribution within a range of -3 to 3 [-3,3]

numpy.random.randn(10)

array([-1.79261103,  0.63901198, -0.47571269, -0.75122564,  0.16767089,
       -1.72318085, -0.02757397,  0.21826687, -0.8518344 , -1.71905861])

In [73]:
numpy.random.randn(2)

array([-0.45476505,  2.19216304])

In [75]:
numpy.random.randn(5,5)

array([[-1.4046302 , -0.39209931,  1.43819065,  0.29561035,  0.13658928],
       [ 0.43137797, -0.50610082, -0.85414018, -0.84760957, -0.87213845],
       [-0.81733448,  0.75479592,  0.15853225, -0.82214884, -1.68578511],
       [ 1.02104045,  0.6184434 ,  0.61954498,  1.97141021,  0.78686525],
       [-0.20185629, -0.81390528,  1.2041122 , -1.82293186,  0.33378028]])

In [82]:
#some questions

#1 Gnerate 10 ranomd integes between 1to 10000
numpy.random.randint(1,10000, size=10)

#1 Gnerate (2x3) ranomd integes between 1to 10000
arr =numpy.random.randint(1,10000, size=(2,3))
print(arr)
print(numpy.max(arr))
print(numpy.argmax(arr))

[[7523 4838 2070]
 [8091 6030 9289]]
9289
5


In [89]:
#Indexing
arr=numpy.random.randint(1,10000, 5)
print(arr)
print("arr[::-1] => ",arr[::-1])

[1914 1306 6039 4476 6099]
arr[::-1] =>  [6099 4476 6039 1306 1914]


In [113]:
#Indexing 2 D array

arr=numpy.random.randint(1,10000, size=(4,3))
print(arr)
print("arr[[0]]=>", arr[[0]])  # 0rd row
print("arr[[0]]=>", arr[[0]])   # 3rd row
print("arr[[0,3]]=>", arr[[0,3]])   # 0 and 3rd row
print("arr[0][2] =>", arr[0][2])   # 0 row and 2 index in 0 row

print("arr[:,[1]] =>", arr[:,[1]])   # 1 st column
print("arr[:,[1]] =>", arr[:,[1,2]])   # 1 and 3 rd column



[[3314 9330  407]
 [2222 3450 6849]
 [5173 2830 7043]
 [7404 7037 3522]]
arr[[0]]=> [[3314 9330  407]]
arr[[0]]=> [[3314 9330  407]]
arr[[0,3]]=> [[3314 9330  407]
 [7404 7037 3522]]
arr[0][2] => 407
arr[:,[1]] => [[9330]
 [3450]
 [2830]
 [7037]]
arr[:,[1]] => [[9330  407]
 [3450 6849]
 [2830 7043]
 [7037 3522]]


In [114]:
# add arrays
arr1= numpy.array([1,2,3,4,5,6])
arr2= numpy.array([1,2,3,4,5,6])
arr1+arr2

array([ 2,  4,  6,  8, 10, 12])

In [127]:
# multiply arrays: respective elements are multiplied if dimensions are same , same for all operations includding additon, * , /
arr1= numpy.array([1,2,3,4,5,6])
arr2= numpy.array([1,2,3,4,5,6])
arr1*arr2


array([ 1,  4,  9, 16, 25, 36])

In [125]:
# divide arrays
arr1= numpy.array([10,20,30,40,50,60.65])
arr2= numpy.array([1,2,3,4,5,6])
arr3=numpy.array([1,2,3,4,5,6])
arr1/arr2
arr2/arr1
arr2/arr3

array([1., 1., 1., 1., 1., 1.])

In [126]:
arr1+5

array([15.  , 25.  , 35.  , 45.  , 55.  , 65.65])